[general]
library_name = "libgclibo"
output_file_path = "../src/libgclib.jl"
module_name = "LibGclib"
prologue_file_path = "./prologue.jl"
use_julia_native_enum_type = false
auto_mutability = true
extract_c_comment_style = "doxygen"
show_c_function_prototype = true
use_deterministic_symbol = true
smart_de_anonymize = true
export_symbol_prefixes = ["G"]

[codegen]
use_julia_bool = true
use_ccall_macro = true
always_NUL_terminated_string = true

[codegen.macro]
# it‘s highly recommended to set this entry to "basic".
# if you'd like to skip all of the macros, please set this entry to "disable".
# if you'd like to translate function-like macros to Julia, please set this entry to "aggressive".
macro_mode = "basic"